<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="AddService" targetNamespace="http://service.demo.ws/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://service.demo.ws/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://service.demo.ws/" schemaLocation="addserviceimpl_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="add">
    <wsdl:part name="parameters" element="ns1:add">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="addResponse">
    <wsdl:part name="parameters" element="ns1:addResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="AddService">
    <wsdl:operation name="add">
      <wsdl:input name="add" message="ns1:add">
    </wsdl:input>
      <wsdl:output name="addResponse" message="ns1:addResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
